### PR TITLE
Implementation

### PR DESCRIPTION
**Pull request by fazo96**
This is basically the same code that was in ChluIPFS, just moved to its own repository

What's missing:

- [ ] unit tests. The collector is very involved in the integration tests so that's not a big deal

### CODE REVIEW

**Comment by kulpreet** [comment]
@fazo96 still WIP?

**Comment by fazo96** [comment]
@kulpreet it's missing the unit tests and any bug fixes from issues that will emerge in the integration tests

But the code itself is good to go and you can review :)

**Comment by kulpreet** [comment]
There's a checkbox in your PR comment. I imagine, I can ignore that?

**Comment by fazo96** [comment]
Yes, I'll open an issue to track that the unit tests aren't implemented. We can live with it due to the module being simple and it being used heavily in the integration tests.

**Pull request merged**
